apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: password-generator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 32
      symbols: 0
      digits: 6
      noUpper: false
      allowRepeat: true
