apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: haproxy-ingress

resources:
  - namespace.yaml

helmCharts:
  - name: haproxy-ingress
    repo: https://haproxy-ingress.github.io/charts
    releaseName: haproxy-ingress
    valuesInline:
      controller:
        kind: DaemonSet
        daemonset:
          useHostPort: true
        service:
          type: ClusterIP
        ingressClassResource:
          enabled: true
