apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 389ds-server
spec:
  secretName: 389ds-tls
  commonName: 389ds.389ds.svc.cluster.local
  duration: 1h
  renewBefore: 30m
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: 389ds-ca
    kind: Issuer
  dnsNames:
    - 389ds
    - 389ds.389ds
    - 389ds.389ds.svc
    - 389ds.389ds.svc.cluster.local
  usages:
    - server auth
