apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - ../shared
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/ha/install.yaml

components:
  - ../components/enable-helm
