apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-dirsrv-ca-reader
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-dirsrv-ca-reader
subjects:
  - kind: ServiceAccount
    name: keycloak-dirsrv-ca-reader
    namespace: keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-dirsrv-ca-reader
