apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dirsrv

labels:
  - pairs:
      component: dirsrv
    includeSelectors: true

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - statefulset.yaml
  - service.yaml
  - config

configMapGenerator:
  - name: dirsrv-custom-schema
    files:
      - schema/98wireguard.ldif
  - name: dirsrv-init-script
    files:
      - init/init.sh
  - name: dirsrv-init-ldif
    files:
      - ldif/config.ldif
      - ldif/backend.ldif

images:
  - name: dirsrv
    newName: registry.redhat.io/dirsrv/dirsrv-container-rhel10
    newTag: "13.2"
