apiVersion: v1
kind: Service
metadata:
  name: dirsrv
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  ports:
    - name: ldap
      port: 3389
      targetPort: ldap
    - name: ldaps
      port: 3636
      targetPort: ldaps
