apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 389ds

labels:
  - pairs:
      component: 389ds
    includeSelectors: true

resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml
  - config

configMapGenerator:
  - name: 389ds-custom-schema
    files:
      - schema/98wireguard.ldif
  - name: 389ds-init-script
    files:
      - init/init.sh
  - name: 389ds-init-ldif
    files:
      - ldif/config.ldif

images:
  - name: 389ds
    newName: docker.io/389ds/dirsrv
    newTag: latest
