apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 389ds
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ldapdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  template:
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: 389ds
          image: 389ds
          envFrom:
            - secretRef:
                name: 389ds-credentials
          ports:
            - containerPort: 3389
              name: ldap
              hostPort: 3389
            - containerPort: 3636
              name: ldaps
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: ldapdata
              mountPath: /data
            - name: ldap-tls
              mountPath: /data/tls
              readOnly: true
            - name: custom-schema
              mountPath: /etc/dirsrv/schema/98wireguard.ldif
              subPath: 98wireguard.ldif
              readOnly: true
        - name: envoy
          image: envoy
          command: ["sh", "/entrypoint/entrypoint.sh"]
          ports:
            - containerPort: 6636
              name: ldaps-tls
              hostPort: 3636
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            tcpSocket:
              port: ldaps-tls
            periodSeconds: 5
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
              readOnly: true
            - name: envoy-entrypoint
              mountPath: /entrypoint
              readOnly: true
            - name: ldap-tls
              mountPath: /etc/envoy/tls
              readOnly: true
            - name: envoy-sds
              mountPath: /etc/envoy/sds
      volumes:
        - name: envoy-config
          configMap:
            name: 389ds-envoy-config
        - name: envoy-entrypoint
          configMap:
            name: 389ds-envoy-entrypoint
        - name: envoy-sds
          emptyDir: {}
