apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: garage
  labels:
    app: garage
spec:
  selector:
    app: garage
  ports:
    - name: s3-api
      port: 3900
      targetPort: s3-api
    - name: admin
      port: 3903
      targetPort: admin
