apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/dirsrv/
  - dirsrv-credentials.yaml
  - sssd-bind-credentials.yaml

# Publish the LDAP ports on fixed NodePorts. cluster.yaml maps these node ports
# to the host.
patches:
  - target:
      kind: Service
      name: dirsrv
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: dirsrv
      spec:
        type: NodePort
        ports:
          - name: ldap
            port: 3389
            nodePort: 30389
          - name: ldaps
            port: 3636
            nodePort: 30636
