apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/larsks/moc-services-config.git
        revision: feature/lldap
        directories:
          - path: PATCHME
  template:
    metadata:
      name: "{{.path.basename}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/larsks/moc-services-config.git
        targetRevision: feature/lldap
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
